refresh_data:
  name: Refresh ADSB Data
  description: Manually refresh aircraft data from ADSB source

test_military_detection:
  name: Test Military Detection
  description: Test military aircraft detection logic with current data
  response:
    optional: true

get_aircraft_details:
  name: Get Aircraft Details
  description: Get detailed information about a specific aircraft by hex code
  fields:
    hex_code:
      name: Aircraft Hex Code
      description: ICAO hex identifier of the aircraft
      required: true
      selector:
        text:
  response:
    optional: true

load_military_database:
  name: Load Military Database
  description: Manually load the military aircraft database from tar1090-db
  response:
    optional: true